### ISSUE TITLE
Not working angular cli 1.0.0-beta.24

### ISSUE THREAD

**Issue by dsl-src** [devyumao/angular2-busy#27] opened 2016-12-31 07:56 UTC
ERROR in BusyModule is not an NgModule

**Comment by adarshakr** [comment] 2017-01-05 14:21
same here

**Comment by tobibrandenberg** [comment] 2017-01-09 13:41
I can confirm that issue

**Comment by thor089** [comment] 2017-01-09 16:55
Unfortunately this issue occurs also in my project since I use angular2-busy.

There is a discussion on angular-cli
https://github.com/angular/angular-cli/issues/3426

It looks like "3rd-party libs needing to publish ng module meta data" in .module.metadata.json in src.

**Comment by beeman** [comment] 2017-01-10 14:53
From the issue mentioned by @thor089 , here is a guide on how to publish an Angular module that might help fixing the issue:

https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464#.3p2xd74qr

**Comment by figuerres** [comment] 2017-01-25 15:24
also the option to set the config with .forRoot also creates error messages with angular cli.
calling functions not allowed is part of the message.

**Comment by figuerres** [comment] 2017-01-25 22:53
i just started a fork from this and will see if i can update it to work with angular cli see here: https://github.com/figuerres/ng-busy
give me a few days and then see if you want to add to this...

**Comment by crowmagnumb** [comment] 2017-01-30 19:21
Did you ever get this working? I too have this problem.

**Comment by figuerres** [comment] 2017-01-30 21:05
@crowmagnumb  please post on my form if you are asking about it.   i have code that will be checked in tomrrow on my fork  [https://github.com/figuerres/ng-busy](url)

i do not yet have it "packaged" for node modules but do have a set of files that work, i just had to update the dependcancies and also get another package updated.
 
please read my new post on my forked site.

**Comment by crowmagnumb** [comment] 2017-02-03 20:08
No thank you @figuerres. I feel you went off in a direction that is too far removed. I'll wait for a simpler fix from within.

**Comment by crowmagnumb** [comment] 2017-02-03 20:10
Although it does feel like this project is abandoned. :)

**Comment by figuerres** [comment] 2017-02-03 20:54
If you get the code from my fork it's the same code I just updated the dependencies on packages so it works with angular click, not sure what you mean ? Just have not had time yet to finish packaging it for npm.

**Closed as completed** 2017-04-19 06:15 UTC
